### ISSUE TITLE
The FlipView defaults to page -1 when using ItemsSource

### ISSUE THREAD

**Issue by stevehemond** [JohanLarsson/Gu.Wpf.FlipView#5]
If I bind to a collection from ItemsSource and specify an ItemTemplate, the FlipView defaults to page -1 when shown. I have to swipe left (or hit the right arrow) to move from that empty page to the first item of the collection.

Here's my XAML : 
```xaml
<flipView:FlipView ItemsSource="{Binding PartitionItem.Pages}" ShowIndex="False">
    <flipView:FlipView.ItemTemplate>
        <DataTemplate>
            <Image Source="{Binding Image}"/>
        </DataTemplate>
    </flipView:FlipView.ItemTemplate>
</flipView:FlipView>
```

<img width="1331" alt="screenshot1" src="https://user-images.githubusercontent.com/30006122/28346405-f45da5f0-6bfe-11e7-88c2-7f52a32db921.png">
<img width="1314" alt="screenshot2" src="https://user-images.githubusercontent.com/30006122/28346406-f461ab5a-6bfe-11e7-8d93-a87533b64bfa.png">

**Comment by stevehemond** [comment]
Sorry I'm new to GitHub, it's the first time I write an issue, I have to improve my use of the code tag :P

**Comment by JohanLarsson** [comment]
This behavior comes from that we inherit [Selector](http://referencesource.microsoft.com/#PresentationFramework/Framework/System/Windows/Controls/Primitives/Selector.cs,326). -1 is a poor default for this control, thanks for reporting!

A quick fix is to set `SelectedIndex="0"` in xaml.

I'll update the code so that it sets to 0 when `ItemsSource` changes and there are items.

**Comment by stevehemond** [comment]
Thanks for the quick response !
